ontic:
  ms:
    client:
      serviceRegistry:
        TestMicroService:
          address: 'localhost:50051'
        contextService:
          address: 'localhost:50051'
        '[helloworld.Greeter]':
          address: 'localhost:50051'
