ontic:
  ms:
    server:
      port: 50051
      serverName: ms-test-server
      maxInboundMetadataSize: 30720
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always